### ISSUE TITLE
Separate providing NBD from attaching NBD?

### ISSUE THREAD

**Issue by joshtriplett** [oll3/nbd-async#1]
Thank you for building this, it looks great!

One request: would you consider separating the interface for responding to NBD requests given a `BlockDevice` implementation from the interface for attaching an NBD socket to the local system? That would make it easy to hook the former up to a server socket, and to use the latter to attach a remote socket to a local NBD device.

**Comment by oll3** [comment]
Sure, sounds like a good idea. Would something like #5 sufficient?

**Comment by joshtriplett** [comment]
That looks promising!

I would reverse the names of the two main functions, though; the function called `serve_nbd` is what I'd call `attach_device` and vice versa. The function that serves NBD protocol over a socket should be called `serve_nbd`, and the function that attaches a socket to a kernel NBD device should be called `attach_device`.

Otherwise, this looks good from inspection.

**Comment by joshtriplett** [comment]
#5 fixed this; closing. Thank you!

**Comment by joshtriplett** [comment]
Would you consider a new `0.2` release with the current changes included?
