### ISSUE TITLE
Error handling in Command::Read

### ISSUE THREAD

**Issue by Emm54321** [oll3/nbd-async#9]
From the documentation for NBD_CMD_READ:

> If an error occurs, the server SHOULD set the appropriate error code
> in the error field. The server MAY then initiate a hard disconnect.
> If it chooses not to, it MUST NOT send any payload for this request.

So it seems to me that after setting reply.error, the reply_buf should be resized back to nbd::SIZE_OF_REPLY before sending the reply.

**Comment by oll3** [comment]
> From the documentation for NBD_CMD_READ:
> 
> > If an error occurs, the server SHOULD set the appropriate error code
> > in the error field. The server MAY then initiate a hard disconnect.
> > If it chooses not to, it MUST NOT send any payload for this request.
> 
> So it seems to me that after setting reply.error, the reply_buf should be resized back to nbd::SIZE_OF_REPLY before sending the reply.

Yes, seems correct. I guess the client could also ensure this behavior but it is probably appropriate to enforce it here too. Is it something like #10 you have in mind @Emm54321 ?

**Comment by Emm54321** [comment]
> Yes, seems correct. I guess the client could also ensure this behavior but it is probably appropriate to enforce it here too. Is it something like #10 you have in mind @Emm54321 ?

Yes, this would fix problem.

**Comment by oll3** [comment]
Closing since fixed with the merge of #10 .
